### ISSUE TITLE
Library plugin stopped working with version 1.4.0

### ISSUE THREAD

**Issue by tadjan** [nebula-plugins/nebula-archrules-plugin#114]
With version 1.4.0 of `com.netflix.nebula.archrules.library` plugin, it seems not to work anymore. Despite being applied, dependency definitions like `archRulesTestImplementation` are not recognized. It used to just work as-is with version 1.3.1

Error:
```
* What went wrong:
Script compilation error:

  Line 14:     archRulesTestImplementation(kotlin("test"))
               ^ Unresolved reference 'archRulesTestImplementation'.

```

Minimal reproduction code: https://github.com/tadjan/archrules-example
Tested agains Gradle version 9.7.1 and 9.6.0

**Comment by tadjan** [comment]
Update: the issue was only with Kotlin projects and including `java-library` plugin alongside `com.netflix.nebula.archrules.library` did the trick.
